### ISSUE TITLE
Broken link on the Github organization page?

### ISSUE THREAD

**Issue by kojix2** [griffithlab/griffithlab.org#23]
Hello. 

I was looking for a workflow for neoantigen prediction and found your great project. 
I clicked the link below to see your website, but I couldn't open the page 
Parhaps the link may have expired ?

Thank you.

 http://www.griffithlab.org

![image](https://user-images.githubusercontent.com/5798442/74299821-313e8900-4d91-11ea-864d-1afea074bbf1.png)

**Comment by zlskidmore** [comment]
should be https:// I think, fixed now

**Comment by zlskidmore** [comment]
actually I only had permissions to fix it on the repo, @obigriffith @malachig I think you'll have to fix on the github landing page

**Comment by obigriffith** [comment]
I'm not sure why this isn't working. I think I might have mistakenly deleted a cname record that allows the www version of our site url to work. I fixed the github landing page and tried to add back a cname record for www. Waiting for it to propagate to see if that works. But, the new url should work either way

**Comment by kojix2** [comment]
Thank you for the quick fix!
