### ISSUE TITLE
Add orcids for lab members?

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/griffithlab.org#24]
Right now we have a few links for each member (GitHub, LinkedIn, etc). I thought it might be good to add the orcid there as well.

**Comment by zlskidmore** [comment]
This should be easy to implement there's an academic font library I just found here that has orcid
https://jpswalsh.github.io/academicons/

**Comment by kcotto** [comment]
I've added the ability to add orcids now and added yours @susannasiebert.
